### ISSUE TITLE
thanks for sharing!

### ISSUE THREAD

**Issue by randomwangran** [guanyilun/cuts.el#1]
`cuts-slurm `is so cool!

**Comment by randomwangran** [comment]
https://github.com/randomwangran/WRE/commit/f64d76b694d093144f076d4d6401eceef8a0f462

**Comment by randomwangran** [comment]
so sweet, I like this piece.

**Comment by guanyilun** [comment]
Thank you! I agree it's a very handy tool that i wish i had before..
